services:
  - type: web
    name: aso-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u main.py
    ignoredPaths:
      - docs/**
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.gif"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/bot.db
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "1"
